services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: signalforge:dev
    container_name: signalforge-api-dev
    ports:
      - "8010:8000"
    environment:
      # Logging + version info (CI can override later)
      - LOG_LEVEL=INFO
      - MODEL_VERSION=${MODEL_VERSION:-unloaded}
      - FEATURESET=${FEATURESET:-none}
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-local}
      - BUILD_TIME=${BUILD_TIME:-${BUILD_TIME_OVERRIDE:-}}
      # Uvicorn concurrency (dev: 1 worker for easier debugging)
      - UVICORN_WORKERS=1
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    profiles: ["dev"]

  api-pi:
    build:
      context: .
      dockerfile: Dockerfile
    image: signalforge:pi
    container_name: signalforge-api-pi
    ports:
      - "8010:8000"
    environment:
      - LOG_LEVEL=INFO
      - MODEL_VERSION=${MODEL_VERSION:-unloaded}
      - FEATURESET=${FEATURESET:-none}
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-local}
      - BUILD_TIME=${BUILD_TIME:-${BUILD_TIME_OVERRIDE:-}}
      # Keep it lightweight on Pi
      - UVICORN_WORKERS=1
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/health"]
      interval: 30s
      timeout: 6s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    profiles: ["pi"]
