[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".git", ".venv", "build", "dist", "__pycache__", "data"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]  # Black handles line length

[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
testpaths = ["tests"]
